# Justfile for fast-api-hello-world

# Show available commands

build:
    samlocal build --template-file infra/template.yaml --config-file samconfig.toml

deploy-localstack: build
    @echo "Deploying to localstack..."

    samlocal deploy --config-file infra/samconfig.toml --no-confirm-changeset

delete-localstack:
    @echo "Deleting poc stack..."
    samlocal delete --stack-name {{cookiecutter.project_slug}} --region us-east-1
