# Justfile for {{cookiecutter.pypi_package_name}}

# LocalStack deployment recipes

build-localstack:
      #!/usr/bin/env bash
      set -e
      # LocalStack uses AWS_ACCESS_KEY_ID as account ID when it's a 12-digit number
      export AWS_ACCESS_KEY_ID=000000000000
      export AWS_SECRET_ACCESS_KEY=test
      samlocal build --template-file infra/template.yaml --config-file samconfig.toml

deploy-localstack: build-localstack
      #!/usr/bin/env bash
      set -e
      # LocalStack uses AWS_ACCESS_KEY_ID as account ID when it's a 12-digit number
      export AWS_ACCESS_KEY_ID=000000000000
      export AWS_SECRET_ACCESS_KEY=test
      samlocal deploy --config-file infra/samconfig.toml --no-confirm-changeset

delete-localstack:
    @echo "Deleting stack from LocalStack..."
    samlocal delete --stack-name {{cookiecutter.pypi_package_name}} --region us-east-1

# AWS deployment recipes

build:
    sam build --template-file infra/template.yaml --config-file samconfig.toml

deploy: build
    @echo "Deploying to AWS..."
    sam deploy --config-file infra/samconfig.toml --no-confirm-changeset

delete:
    @echo "Deleting stack from AWS..."
    sam delete --stack-name {{cookiecutter.pypi_package_name}} --region us-east-1
