# Justfile for fast-api-hello-world

# Show available commands

build:
    samlocal build --template-file infra/template.yaml --config-file samconfig.toml

deploy-poc: build
    @echo "Deploying to poc..."

    samlocal deploy --config-file infra/samconfig.toml --no-confirm-changeset --stack-name fast-api-hello-world-poc

delete-poc:
    @echo "Deleting poc stack..."
    samlocal delete --stack-name fast-api-hello-world-poc --region us-east-1
